[View in Colaboratory](https://colab.research.google.com/github/harekrishnamahto9872/Acadview/blob/master/Metrics_Assignment.ipynb)

In [0]:
import numpy as np
import pandas as pd

In [0]:
from sklearn.datasets import load_digits

In [0]:
df=load_digits()

In [7]:
df.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [8]:
df.data.shape

(1797, 64)

In [10]:
df.target

array([0, 1, 2, ..., 8, 9, 8])

In [11]:
df.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [12]:
df.target[0]

0

In [0]:
x=df.data

In [0]:
y=df.target

In [15]:
type(x)

numpy.ndarray

In [16]:
type(y)

numpy.ndarray

In [0]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split 
from sklearn import model_selection

##Splitting data into train and test variable

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [0]:
obj=linear_model.LogisticRegression()

##Training our model on training data

In [21]:
obj.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

##Making predictions

In [0]:
predicted=obj.predict(x_test)


##Printing score

In [33]:
obj.score(x_test,y_test)

0.9518518518518518

In [0]:
import sklearn.metrics as met

In [0]:
prob=obj.predict_proba(x_test)

##Printing log loss score

In [0]:
result=met.log_loss(y_test,prob)

In [50]:
print(result)

0.26338134201320706


##Printing Accuracy score

In [0]:
result=met.accuracy_score(y_test,predicted)

In [52]:
print(result)

0.9518518518518518


##Printing R2 score

In [0]:
result=met.r2_score(y_test,predicted)

In [54]:
print(result)

0.8683867179855176


##Printing Mean Absolute Error

In [0]:
result=met.mean_absolute_error(y_test,predicted)

In [56]:
print(result)

0.1962962962962963


##Printing Mean Squared Error

In [0]:
result=met.mean_squared_error(y_test,predicted)

In [58]:
print(result)

0.9962962962962963


##Printing Confusion Matrix

In [0]:
matrix=met.confusion_matrix(y_test,predicted)

In [60]:
print(matrix)

[[49  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  2  1]
 [ 0  0 62  1  0  0  0  0  0  0]
 [ 0  0  0 47  0  1  1  0  4  1]
 [ 0  1  0  0 57  0  0  0  0  3]
 [ 0  0  0  0  0 60  0  0  0  2]
 [ 0  0  0  0  1  0 52  0  0  0]
 [ 0  0  0  0  0  0  0 51  0  1]
 [ 0  1  0  1  0  1  0  0 41  2]
 [ 0  0  0  0  0  1  0  0  1 40]]


##Printing Classification report

In [0]:
report=met.classification_report(y_test,predicted)

In [62]:
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        49
          1       0.96      0.95      0.96        58
          2       1.00      0.98      0.99        63
          3       0.96      0.87      0.91        54
          4       0.98      0.93      0.96        61
          5       0.95      0.97      0.96        62
          6       0.98      0.98      0.98        53
          7       1.00      0.98      0.99        52
          8       0.85      0.89      0.87        46
          9       0.80      0.95      0.87        42

avg / total       0.95      0.95      0.95       540

