[View in Colaboratory](https://colab.research.google.com/github/harekrishnamahto9872/Acadview/blob/master/PCA.ipynb)

In [0]:
import numpy as np
import pandas as pd

In [0]:
from sklearn.datasets import load_digits

##Importing dataset

In [0]:
df=load_digits()

In [0]:
x=df.data

In [0]:
y=df.target

In [88]:
x.shape

(1797, 64)

##Performing standarization on features

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
x=StandardScaler().fit_transform(x)

In [0]:
from sklearn.decomposition import PCA

In [0]:
pca=PCA(n_components=48)

##Perform PCA on Features

In [0]:
x=pca.fit_transform(x)

In [0]:
new_df=pd.DataFrame(data=x,columns=range(1,49))

In [95]:
type(new_df)

pandas.core.frame.DataFrame

In [0]:
y=pd.DataFrame(data=y)


In [98]:
y.head()

0
0  0
1  1
2  2
3  3
4  4

In [0]:
new_df=pd.concat([new_df,y],axis=1)

In [100]:
new_df.head()

1         2         3         4         5         6         7   \
0  1.914214 -0.954502 -3.946035  2.028723 -0.267173  0.530327 -1.415321   
1  0.588980  0.924636  3.924755 -1.779850 -0.993430 -0.675652  1.878565   
2  1.302039 -0.317189  3.023333 -2.043376 -2.081155  0.935121 -1.296201   
3 -3.020770 -0.868772 -0.801744 -2.187039 -0.556813  0.727124  0.959765   
4  4.528949 -1.093480  0.973121 -1.419510 -1.715106  1.431592  1.073649   

         8         9         10 ...        40        41        42        43  \
0  1.496062  0.124915 -0.822246 ...  0.320838  0.013821 -0.046470 -0.286032   
1  0.556335  1.079877  0.087452 ... -0.488790 -0.002525  0.200627 -0.252534   
2  1.156161  0.785606 -1.099207 ...  0.544586 -0.343117 -0.462089  0.046102   
3 -1.382638  0.259075  0.744554 ... -0.048659  0.502720 -0.596673  0.624257   
4 -0.968240 -1.660216  1.174593 ...  0.183594 -0.185453  1.111456 -0.265309   

         44        45        46        47        48  0   
0  0.484896  0.428990 -0.147949  0.097244  0.421569   0  
1  0.691117 -0.094202  0.017594 -0.530220 -0.141202   1  
2  0.558616 -1.069433 -0.642099 -0.570910  0.348749   2  
3 -0.610757 -0.690048  0.433377 -0.182024  0.018477   3  
4 -0.075829  0.298060  0.830744  0.851325 -0.344422   4  

[5 rows x 49 columns]

##Splitting dataset into X and Y

In [0]:
x=new_df.drop([0],axis=1)
y=new_df[0]

##Splitting dataset into train and test

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
obj=LogisticRegression()

In [106]:
x_train.shape

(1437, 48)

In [107]:
y_train.shape

(1437,)

##Training our model

In [108]:
obj.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [0]:
predicted=obj.predict(x_test)

In [0]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

##Evaluation of our model

In [112]:
print(accuracy_score(y_test,predicted))

0.9638888888888889


In [113]:
print(confusion_matrix(y_test,predicted))

[[27  0  0  0  0  0  0  0  0  0]
 [ 0 36  1  0  0  0  0  0  0  0]
 [ 0  0 44  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  1  0  0]
 [ 0  0  0  0 33  0  0  0  0  2]
 [ 1  0  0  0  0 42  0  0  0  2]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  1]
 [ 0  1  0  0  0  0  1  0 29  0]
 [ 0  1  0  0  0  0  0  0  2 31]]


In [114]:
print(classification_report(y_test,predicted))

             precision    recall  f1-score   support

          0       0.96      1.00      0.98        27
          1       0.95      0.97      0.96        37
          2       0.98      1.00      0.99        44
          3       1.00      0.97      0.99        34
          4       1.00      0.94      0.97        35
          5       1.00      0.93      0.97        45
          6       0.97      1.00      0.99        36
          7       0.97      0.97      0.97        37
          8       0.94      0.94      0.94        31
          9       0.86      0.91      0.89        34

avg / total       0.97      0.96      0.96       360

