[View in Colaboratory](https://colab.research.google.com/github/harekrishnamahto9872/Acadview/blob/master/Support_vector_machine.ipynb)

In [0]:
import numpy as np
import pandas as pd

In [0]:
from sklearn.datasets import load_digits

##Importing dataset

In [0]:
df=load_digits()

In [4]:
df.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
df.target

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
df.data.shape

(1797, 64)

In [8]:
df.target.shape

(1797,)

In [0]:
from sklearn.model_selection import train_test_split

##Storing values in X and Y

In [0]:
x=df.data

In [0]:
y=df.target

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [0]:
from sklearn.svm import  SVC
from sklearn.metrics import confusion_matrix,classification_report

##Creating an instance of SVC classifier

##Linear  Kernel

In [0]:
obj=SVC(kernel='linear')

In [16]:
obj.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
predicted=obj.predict(x_test)

In [20]:
print(confusion_matrix(y_test,predicted))

[[49  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  1  0]
 [ 0  0 60  0  0  0  0  0  0  0]
 [ 0  0  0 61  0  0  0  1  0  0]
 [ 0  1  0  0 58  0  0  0  0  0]
 [ 0  0  0  0  0 53  1  0  0  0]
 [ 1  0  0  0  0  0 43  0  0  0]
 [ 0  0  0  0  0  0  0 42  0  0]
 [ 0  1  0  0  0  1  0  0 53  0]
 [ 0  1  0  1  0  0  0  1  1 58]]


In [21]:
print(classification_report(y_test,predicted))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        49
          1       0.95      0.98      0.96        53
          2       1.00      1.00      1.00        60
          3       0.98      0.98      0.98        62
          4       1.00      0.98      0.99        59
          5       0.98      0.98      0.98        54
          6       0.98      0.98      0.98        44
          7       0.95      1.00      0.98        42
          8       0.96      0.96      0.96        55
          9       1.00      0.94      0.97        62

avg / total       0.98      0.98      0.98       540



##Polynomial Kernel

In [0]:
obj=SVC(kernel='poly')

In [23]:
obj.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
predicted=obj.predict(x_test)

In [25]:
print(confusion_matrix(y_test,predicted))

[[49  0  0  0  0  0  0  0  0  0]
 [ 0 53  0  0  0  0  0  0  0  0]
 [ 0  0 60  0  0  0  0  0  0  0]
 [ 0  0  0 61  0  0  0  1  0  0]
 [ 0  0  0  0 59  0  0  0  0  0]
 [ 0  0  0  0  0 53  1  0  0  0]
 [ 0  0  0  0  0  0 43  0  1  0]
 [ 0  0  0  0  0  0  0 42  0  0]
 [ 0  1  0  0  0  0  0  0 54  0]
 [ 0  0  0  0  0  0  0  1  2 59]]


##Gaussian or rbf Kernel

In [0]:
obj=SVC(kernel='rbf')

In [27]:
obj.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
predicted=obj.predict(x_test)

In [30]:
print(confusion_matrix(y_test,predicted))

[[25  0  0  0  0  0  0 24  0  0]
 [ 0 11  0  0  0  0  0 42  0  0]
 [ 0  0  5  0  0  0  0 55  0  0]
 [ 0  0  0  8  0  0  0 54  0  0]
 [ 0  0  0  0 17  0  0 42  0  0]
 [ 0  0  0  0  0 17  0 37  0  0]
 [ 0  0  0  0  0  0 28 16  0  0]
 [ 0  0  0  0  0  0  0 42  0  0]
 [ 0  0  0  0  0  0  0 54  1  0]
 [ 0  0  0  0  0  0  0 58  0  4]]


In [31]:
print(classification_report(y_test,predicted))

             precision    recall  f1-score   support

          0       1.00      0.51      0.68        49
          1       1.00      0.21      0.34        53
          2       1.00      0.08      0.15        60
          3       1.00      0.13      0.23        62
          4       1.00      0.29      0.45        59
          5       1.00      0.31      0.48        54
          6       1.00      0.64      0.78        44
          7       0.10      1.00      0.18        42
          8       1.00      0.02      0.04        55
          9       1.00      0.06      0.12        62

avg / total       0.93      0.29      0.33       540



##Sigmoid Kernel

In [0]:
obj=SVC(kernel='sigmoid')

In [33]:
obj.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
predicted=obj.predict(x_test)

In [35]:
print(confusion_matrix(y_test,predicted))

[[ 0  0  0  0  0  0  1 48  0  0]
 [ 0  0  0  0  0  0  0 53  0  0]
 [ 0  0  0  0  0  0  1 59  0  0]
 [ 0  0  0  0  0  0  0 62  0  0]
 [ 0  0  0  0  0  0  0 59  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  0  0  0  0  0  1 43  0  0]
 [ 0  0  0  0  0  0  1 41  0  0]
 [ 0  0  0  0  0  0  0 55  0  0]
 [ 0  0  0  0  0  0  0 62  0  0]]


In [37]:
print(classification_report(y_test,predicted))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        49
          1       0.00      0.00      0.00        53
          2       0.00      0.00      0.00        60
          3       0.00      0.00      0.00        62
          4       0.00      0.00      0.00        59
          5       0.00      0.00      0.00        54
          6       0.25      0.02      0.04        44
          7       0.08      0.98      0.14        42
          8       0.00      0.00      0.00        55
          9       0.00      0.00      0.00        62

avg / total       0.03      0.08      0.01       540



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
